DEFINE DYNAMIC TABLE ECOMMERCE.ANALYTICS.DT_DAILY_REVENUE
WAREHOUSE = 'ECOMMERCE_WH'
TARGET_LAG = '1 hour'
INITIALIZE = 'ON_CREATE'
AS
SELECT
    DATE_TRUNC('DAY', o.ORDER_DATE) AS ORDER_DAY,
    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    SUM(o.TOTAL_AMOUNT) AS DAILY_REVENUE
FROM ECOMMERCE.RAW.ORDERS o
WHERE o.STATUS != 'CANCELLED'
GROUP BY ORDER_DAY;

DEFINE DYNAMIC TABLE ECOMMERCE.ANALYTICS.DT_PRODUCT_PERFORMANCE
WAREHOUSE = 'ECOMMERCE_WH'
TARGET_LAG = '1 hour'
INITIALIZE = 'ON_CREATE'
AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    COUNT(DISTINCT oi.ORDER_ID) AS TIMES_ORDERED,
    SUM(oi.QUANTITY) AS TOTAL_UNITS_SOLD,
    SUM(oi.QUANTITY * oi.UNIT_PRICE * (1 - oi.DISCOUNT_PCT/100)) AS TOTAL_REVENUE,
    AVG(oi.DISCOUNT_PCT) AS AVG_DISCOUNT
FROM ECOMMERCE.RAW.PRODUCTS p
JOIN ECOMMERCE.RAW.ORDER_ITEMS oi ON p.PRODUCT_ID = oi.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY;

DEFINE DYNAMIC TABLE ECOMMERCE.ANALYTICS.DT_CUSTOMER_LIFETIME_VALUE
WAREHOUSE = 'ECOMMERCE_WH'
TARGET_LAG = 'DOWNSTREAM'
INITIALIZE = 'ON_CREATE'
AS
SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
    c.EMAIL,
    c.REGION,
    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
    SUM(o.TOTAL_AMOUNT) AS LIFETIME_VALUE,
    MIN(o.ORDER_DATE) AS FIRST_ORDER,
    MAX(o.ORDER_DATE) AS LAST_ORDER,
    DATEDIFF('day', MIN(o.ORDER_DATE), MAX(o.ORDER_DATE)) AS CUSTOMER_TENURE_DAYS
FROM ECOMMERCE.RAW.CUSTOMERS c
LEFT JOIN ECOMMERCE.RAW.ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, c.EMAIL, c.REGION;
