DEFINE VIEW ECOMMERCE.SERVE.V_REVENUE_DASHBOARD
AS
SELECT
    ORDER_DAY,
    TOTAL_ORDERS,
    UNIQUE_CUSTOMERS,
    DAILY_REVENUE,
    DAILY_REVENUE / NULLIF(TOTAL_ORDERS, 0) AS AVG_ORDER_VALUE
FROM ECOMMERCE.ANALYTICS.DT_DAILY_REVENUE
ORDER BY ORDER_DAY DESC;

DEFINE VIEW ECOMMERCE.SERVE.V_TOP_PRODUCTS
AS
SELECT
    PRODUCT_NAME,
    CATEGORY,
    TIMES_ORDERED,
    TOTAL_UNITS_SOLD,
    TOTAL_REVENUE,
    AVG_DISCOUNT
FROM ECOMMERCE.ANALYTICS.DT_PRODUCT_PERFORMANCE
WHERE TOTAL_UNITS_SOLD > 0
ORDER BY TOTAL_REVENUE DESC;

DEFINE VIEW ECOMMERCE.SERVE.V_HIGH_VALUE_CUSTOMERS
AS
SELECT
    CUSTOMER_NAME,
    EMAIL,
    REGION,
    TOTAL_ORDERS,
    LIFETIME_VALUE,
    FIRST_ORDER,
    LAST_ORDER,
    CUSTOMER_TENURE_DAYS
FROM ECOMMERCE.ANALYTICS.DT_CUSTOMER_LIFETIME_VALUE
WHERE LIFETIME_VALUE > 500
ORDER BY LIFETIME_VALUE DESC;
