DEFINE TABLE ECOMMERCE.RAW.CUSTOMERS (
    CUSTOMER_ID NUMBER NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(200),
    REGION VARCHAR(50),
    SIGNUP_DATE DATE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
)
CHANGE_TRACKING = TRUE
COMMENT = 'Customer master data from CRM';

DEFINE TABLE ECOMMERCE.RAW.PRODUCTS (
    PRODUCT_ID NUMBER NOT NULL,
    PRODUCT_NAME VARCHAR(200),
    CATEGORY VARCHAR(100),
    UNIT_PRICE NUMBER(10,2),
    SUPPLIER VARCHAR(100),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CHANGE_TRACKING = TRUE
COMMENT = 'Product catalog from ERP';

DEFINE TABLE ECOMMERCE.RAW.ORDERS (
    ORDER_ID NUMBER NOT NULL,
    CUSTOMER_ID NUMBER NOT NULL,
    ORDER_DATE TIMESTAMP_NTZ,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    TOTAL_AMOUNT NUMBER(12,2),
    SHIPPING_ADDRESS VARCHAR(500),
    PAYMENT_METHOD VARCHAR(50)
)
CHANGE_TRACKING = TRUE
COMMENT = 'Order transactions from POS system';

DEFINE TABLE ECOMMERCE.RAW.ORDER_ITEMS (
    ITEM_ID NUMBER NOT NULL,
    ORDER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    DISCOUNT_PCT NUMBER(5,2) DEFAULT 0
)
CHANGE_TRACKING = TRUE
COMMENT = 'Line items for each order';
